# Generated by Django 4.2.3 on 2023-10-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
    ]
