# Generated by Django 4.2.3 on 2023-10-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=50),
        ),
    ]
