# Generated by Django 4.2.6 on 2023-10-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_taskdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('completed', 'completed')], default='In Progress', max_length=50),
        ),
    ]
